name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: install constructor
        run: conda install -c conda-forge constructor
      - name: Build
        run: |
          $CONDA/bin/constructor --platform linux-64 ./F22-06325/condacolab-installer/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./06325-condacolab-v0.0.1-Linux-x86_64.sh
